spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_test?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: root
    password: 123456
logging:
  level:
    com.liam.autotest.sys.dao: trace
server:
  servlet:
    context-path: /api
